- .vscode/settings.json
- articles/admin.py
- articles/models.py
- articles/urls.py
- dsproject/settings.py
- dsproject/urls.py
- requirements.txt
- users/models.py
> feat: Article,Tag,TagList모델추가

- reports/admin.py
- reports/models.py
- users/admin.py
> fix: did'nt commit

- articles/models.py
- emoticons/models.py
- emoticons/serializers.py
- emoticons/urls.py
- emoticons/views.py
댓글모델에 유저모델 연결
이모티콘 CRUD views, serializer 추가
> feat: 이모티콘 CRUD views, serializer추가

- articles/serializers.py
- articles/urls.py
- articles/views.py
- emoticons/models.py
- emoticons/serializers.py
- emoticons/views.py
> feat: (댓글) 댓글 CRUD

- reports/models.py
- reports/serializers.py
- reports/views.py
> style: report

- dsproject/settings.py
refactor: secret file function
> refactor: secret file function

- articles/models.py
- articles/serializers.py
- articles/views.py
> feat: 태그기능구현

- articles/admin.py
- articles/models.py
- articles/serializers.py
- articles/views.py
> feat: create article

- users/models.py
- users/urls.py
- users/views.py
유저 모델, url, 카카오 로그인 view 수정했습니다!!
> fix: 카카오 로그인 be 수정

- .gitignore
- articles/views.py
- users/models.py
- users/urls.py
- users/views.py
> feat: article_loaction unique

- articles/admin.py
- articles/models.py
- articles/serializers.py
- articles/views.py
- users/views.py
> feat: 다중이미지 추가기능 구현

- articles/models.py
- articles/serializers.py
- articles/tests.py
- articles/urls.py
- articles/views.py
- emoticons/models.py
- emoticons/tests.py
- emoticons/views.py
- reports/urls.py
> test: emoticon test code

- emoticons/serializers.py
- emoticons/tests.py
- emoticons/views.py
- reports/serializers.py
1. 프론트 결제정보용 유저 username, email 보내주기
2. 이모티콘 테스트코드 마무리
> feat: username, email for payment / test: emoticon test

- articles/serializers.py
- emoticons/models.py
- emoticons/serializers.py
- emoticons/urls.py
- emoticons/views.py
1. 이모티콘 누적판매량 조회관련 추가
2. 기본이모티콘 경로 수정
> feat: (emoticon) 누적 판매량

- articles/views.py
- dsproject/settings.py
- users/models.py
- users/urls.py
- users/views.py
> feat: 네이버, 구글 로그인 fe,be 연결완료

- articles/serializers.py
- articles/views.py
- reports/views.py
feat: article imgs, report-reporter
> feat: article imgs, report-reporter

- articles/views.py
- emoticons/admin.py
- emoticons/models.py
- emoticons/serializers.py
- emoticons/views.py
이모티콘 생성시 이미지 용량 체크, DB저장
백에서 저장된 DB로 이모티콘 가격책정
> feat: 이모티콘 용량체크, 가격책정

- users/urls.py
> fix: user 프로필 url주소 변경

- users/serializers.py
- users/urls.py
- users/views.py
> fix: 마이페이지 수정

- articles/serializers.py
- articles/views.py
- emoticons/admin.py
- emoticons/urls.py
게시글 수정 가능합니다
이모티콘이미지 어드민 필드 추가, 안쓰게 된 뷰 삭제
> feat: article update 

- articles/views.py
[fix: article create response]
> fix: article create response

- reports/serializers.py
- reports/views.py
> feat: category CRU

- articles/models.py
추가로 그냥이미지도 더직관적이게 디렉토리 이름수정했습니다
> style: main_image 업로드 경로 수정

- reports/views.py
> fix: report message

- dsproject/settings.py
- emoticons/views.py
결제완료시 DB저장방식 변경
기존 프론트에서 받은 결제정보로 DB저장방식에서
결제완료시 백에서 포트원 api요청 후 결제정보 유효성 검사진행 후 DB저장으로 변경
프론트도 업데이트 완료했습니다 프론트 같이 업데이트 필요합니다.
공유드린 API키 secret 추가 필수
> fix: 결제완료 관련 DB저장 조작 이슈 수정 (refactor 결제완료시 DB저장 방식 변경)

- README.md
> doc- readme
